project:
  type: website
  output-dir: Homepage

website:
  title: "David Corcoran"
  favicon: "assets/gu-logo.png"
  back-to-top-navigation: true
  navbar:
    title: David Corcoran
    search: true
    left:
      - text: Homepage
        href: https://corcoran.georgetown.domains/Homepage/index.html
      - text: Introduction
        href: ./index.qmd
      - text: Results
        href: ./results.qmd
      - text: Report
        href: ./report.qmd
    right:
      - icon: github
        href: https://github.com/dcorc7
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/david-corcoran-70677917a/
        aria-label: LinkedIn

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    toc-title: Table of Contents
    css: ./stylesheets/styles.css



